### ISSUE TITLE
Deployment To Now Fails

### ISSUE THREAD

**Issue by nonfungibletunji** [JohnRSim/sapperTransition#1]
Error: Cannot find module 'crossfade'

why is the node_modules folder, inside the src? how can crossfade.js appear as a module in a now deployment. the sample code works locally.

**Comment by JohnRSim** [comment]
https://github.com/sveltejs/realworld/tree/master/src

**Comment by stunjiturner** [comment]
So just add the crossfade.js to the actual node_modules folder

**Comment by nonfungibletunji** [comment]
But why isn't the node_module picked up when deployed to now.

**Comment by JohnRSim** [comment]
this repo is just an example for following up on a bug with svelte and transitions with crossfade and should not be used - https://github.com/sveltejs/svelte/issues/4111
